# Longest common subsequence problem 最长公共子序列问题
给定两个序列$ X = (x_1, x_2, ..., x_m)$ 与 $Y=(y_1,y_2,...,y_n)， 求 $X$和$Y$的最长公共子序列。

* 子序列：将序列中零个或多个元素去掉后得到的序列；
* 公共子序列：给定两个序列X和Y，如果Z既是X的子序列又是Y的子序列，则Z是X和Y的公共子序列。

## LCS最优子结构   
设两个序列 $X = (x_1, x_2, ..., x_m)$ 与 $Y=(y_1,y_2,...,y_n)$的最优子序列为$ Z = (z_1, z_2, ..., z_k)$ 为X和Y的任意LCS，则有：   
* if $x_m = y_n$, then $z_k = x_m = y_n$, and $Z_{k-1}$是 $X_{m-1}$和$Y_{n-1}$的一个LCS.
* if $x_m \ne y_n$, and $z_k \ne x_m$, then Z is a LCS of $X_{m-1}$ and $Y_n$.
* If $x_m \ne y_n$, and $z_k \ne y_n$, then Z is a LCS of $X_m$ and $Y_{n-1}$.

## Recursive solution
设$c(i,j)$ 为 $X_i$ 与 $Y_j$的LCS的长度。则有：   
    \begin{equation}
        c(i,j) = \begin{cases}
                    0,   & \text{if } i=0 \text{ or } j = 0 \\
                    c(i-1, j-1) + 1,   & \text{if } i,j >0 \text{ and } x_i = y_j \\
                    max(c(i-1, j), c(i, j-1)),   & \text{if } x_i \ne y_j
                    \end{cases}
    \end{equation}

## Python implementation
### from bottom to up
c保存 $c(i,j)$的值，b保存子问题的最优解。

In [11]:
import numpy as np

def LCS(x, y):
    m = len(x)
    n = len(y)
    c = np.zeros((m+1,n+1))
    b = np.asarray([[None]*n]*m)
    for i in range(1,m+1):
        for j in range(1, n+1):
            if x[i-1] == y[j-1]:
                c[i][j] = c[i-1][j-1] + 1
                b[i-1][j-1] = 'nw'
            elif c[i-1][j] >= c[i][j-1]:
                c[i][j] = c[i-1][j]
                b[i-1][j-1] = 'u'
            else:
                c[i][j] = c[i][j-1]
                b[i-1][j-1] = 'l'
    return c, b


def print_LCS(b, x, m, n):
    """m,n: Lenght of X and Y"""
    if m == 0 or n == 0:
        return None
    elif b[m-1][n-1] == 'nw':
        print_LCS(b,x, m-1, n-1)
        print(x[m-1],end = ' ')
    elif b[m-1][n-1] == 'u':
        print_LCS(b, x, m-1, n)
    else: #b[m][n] == 'l'
        print_LCS(b, x, m, n-1)
        
x = ['A', 'B', 'C', 'B', 'D', 'A', 'B']
y = ['B', 'D', 'C', 'A', 'B', 'A']
m=len(x); n=len(y)
c, b = LCS(x, y)
print('c=',c)
print('The LCS is: ')
print_LCS(b,x, m, n)

c= [[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  1.  1.]
 [ 0.  1.  1.  1.  1.  2.  2.]
 [ 0.  1.  1.  2.  2.  2.  2.]
 [ 0.  1.  1.  2.  2.  3.  3.]
 [ 0.  1.  2.  2.  2.  3.  3.]
 [ 0.  1.  2.  2.  3.  3.  4.]
 [ 0.  1.  2.  2.  3.  4.  4.]]
The LCS is: 
B C B A 