# Knapsack problem
## description
* Have a list of n items, each with:  
    * size $s_i$, _integrer_
    * value, $v_i$
* Have a knapsack of total size: $S$.
* Goal: find out a subset A, such that 
    ![](http://latex.codecogs.com/gif.latex?\begin{align*}             & \max{ \sum_{i\in A} v_i} \\       s.t.  & \sum_{i \in A} s_i \le S    \end{align*})


## Analysis
* 对于某个item，有选与不选两种选择；设D(i)表示在i个item中选择一个子集其总体积不超过S时能得到的最大的value，则有：
    \begin{equation}
        D(i) = \max \{D(i-1), D(i-1)+v_i\}
    \end{equation}
    但这显然不对，前一个D(i-1)表示不选择第i个item，后一个表示选择，两种情况有着不同的size。但式子里并没有体现出来。
* 修改为：D(i, x), x表示剩余的capacity，则有：
     \begin{align*}
        D(i,x) =\begin{cases}
                    &\max \{D(i-1, x), D(i-1, x-s_i)+v_i\} & \text{ otherwise}\\
                    &D(i-1, x),   & \text{ if } s_i > x \\
                    &0, & \text{ if } i = 0
                    \end{cases}
    \end{align*}
*  \# of subproblems: $\Theta(nS)$.   
    time = $\Theta(nS)$.

## Python implementation
* 自底向上方法按选择的item个数从0到n来实现算法，因此，程序必须对每一对$(i, x)$, s.t $0\le i \le$ #item, $0\le x \le S$都计算出一个值

In [9]:
import numpy as np
def knapsack(p, S):
    m = len(p) + 1
    n = S + 1
    c = np.zeros((m,n))
   # b = np.zeros(len(p))
    
    for i in range(1, m):
        for x in range(1,n):
            if p[i-1][0] > x:
                #b[i-1] = 0
                c[i][x] = c[i-1][x]
            else:
                if c[i-1][x] > c[i-1][x-p[i-1][0]] + p[i-1][1]:
                    c[i][x] = c[i-1][x]
                else:
                    #b[i][x] = 1 
                    c[i][x] = c[i-1][x-p[i-1][0]] + p[i-1][1]
    return c              
    
p = [(1,1), (2, 6), (5, 18), (6, 22), (7, 28)] # p[i] = (s, v), s为item p[i] 的size, v为item p[i] 的value.    
S = 11
c = knapsack(p, S)
print('c=\n',c)

c=
 [[  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  0.   1.   6.   7.   7.   7.   7.   7.   7.   7.   7.   7.]
 [  0.   1.   6.   7.   7.  18.  19.  24.  25.  25.  25.  25.]
 [  0.   1.   6.   7.   7.  18.  22.  24.  28.  29.  29.  40.]
 [  0.   1.   6.   7.   7.  18.  22.  28.  29.  34.  35.  40.]]


* from top to bottom

In [11]:
import numpy as np

inf = float('inf')
def knapsack_1(p, i, x):
    
    #mem = np.zeros((m,n))

    if mem[i][x] != inf:
        return mem[i][x]
    elif i == 0:
        mem[i][x] = 0
    elif p[i-1][0] > x:
        mem[i][x] = knapsack_1(p, i-1, x)
    else:
        mem[i][x] = max(knapsack_1(p, i-1, x), knapsack_1(p, i-1, x-p[i-1][0])+ p[i-1][1])
    return mem[i][x]

p = [(1,1), (2, 6), (5, 18), (6, 22), (7, 28)] # p[i] = (s, v), s为item p[i] 的size, v为item p[i] 的value.    
S = 11
m = len(p) + 1
n = S + 1
mem = np.asarray([[inf]*n]*m)
c = knapsack_1(p, len(p), S)
print('c=\n',c)
print('mem = \n', mem)

c=
 40.0
mem = 
 [[  0.   0.   0.   0.   0.   0.   0.  inf   0.   0.   0.   0.]
 [  0.  inf   1.   1.   1.   1.   1.  inf  inf   1.  inf   1.]
 [  0.  inf  inf  inf   7.   7.   7.  inf  inf  inf  inf   7.]
 [ inf  inf  inf  inf   7.  18.  inf  inf  inf  inf  inf  25.]
 [ inf  inf  inf  inf   7.  inf  inf  inf  inf  inf  inf  40.]
 [ inf  inf  inf  inf  inf  inf  inf  inf  inf  inf  inf  40.]]
